// Generates crates/stucco-ui/src/icon/lucide.rs from the lucide-static package.
// Run: cd tools && npm install && npm run icons
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "node_modules", "lucide-static");
const { version } = JSON.parse(await readFile(join(pkg, "package.json"), "utf8"));
const dir = join(pkg, "icons");
const files = (await readdir(dir)).filter((f) => f.endsWith(".svg")).sort();

const lines = [
  `//! The Lucide icon set (lucide-static ${version}, ISC licence; see LICENSE-LUCIDE).`,
  "//! Generated by tools/gen-icons.mjs — do not edit.",
  "",
  "use super::Icon;",
  "",
];
const idents = [];
for (const file of files) {
  const name = file.slice(0, -".svg".length);
  const svg = (await readFile(join(dir, file), "utf8")).replace(/<!--[\s\S]*?-->/g, "");
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
  if (/<script|\son\w+\s*=|href|"#/i.test(body)) throw new Error(`unsafe or unexpected icon body: ${name}`);
  let ident = name.toUpperCase().replace(/[^A-Z0-9]+/g, "_");
  if (/^[0-9]/.test(ident)) ident = `N${ident}`;
  if (!/^[A-Z][A-Z0-9_]*$/.test(ident)) throw new Error(`bad identifier for ${name}`);
  idents.push(ident);
  lines.push(`/// Lucide \`${name}\`.`);
  lines.push(`pub const ${ident}: Icon = Icon::custom("${name}", r#"${body}"#);`);
}
lines.push("", "/// Every icon in the set, sorted by name.", "pub const ALL: &[Icon] = &[");
for (const ident of idents) lines.push(`    ${ident},`);
lines.push("];", "");

const out = join(here, "..", "crates", "stucco-ui", "src", "icon", "lucide.rs");
await writeFile(out, lines.join("\n"));
console.log(`wrote ${idents.length} icons (lucide-static ${version}) to ${out}`);
