// Generates crates/stucco-ui/src/icon/lucide.rs from the lucide-static package.
// Run: cd tools && npm install && npm run icons
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "node_modules", "lucide-static");
const { version } = JSON.parse(await readFile(join(pkg, "package.json"), "utf8"));
const dir = join(pkg, "icons");
const files = (await readdir(dir)).filter((f) => f.endsWith(".svg")).sort();

// Allowlist: only self-closing plain shapes with geometry attributes and
// double-quoted values. Mirrored by is_plain_shape_markup in icon.rs. (A
// multi-line element fused by the newline removal below fails this check.)
const ELEMENTS = new Set(["path", "circle", "rect", "line", "polyline", "polygon", "ellipse"]);
const ATTRIBUTES = new Set([
  "d", "cx", "cy", "r", "rx", "ry", "x", "y", "x1", "x2", "y1", "y2", "width", "height", "points", "fill",
]);
function isPlainShapes(body) {
  const tag = /^<([a-z]+)((?:\s+[a-z0-9]+="[^"<>]*")*)\s*\/>/;
  let rest = body.trim();
  while (rest) {
    const m = tag.exec(rest);
    if (!m || !ELEMENTS.has(m[1])) return false;
    for (const a of m[2].matchAll(/([a-z0-9]+)="/g)) if (!ATTRIBUTES.has(a[1])) return false;
    rest = rest.slice(m[0].length).trimStart();
  }
  return true;
}

const lines = [
  `//! The Lucide icon set (lucide-static ${version}, ISC licence; see LICENSE-LUCIDE).`,
  "//! Generated by tools/gen-icons.mjs — do not edit.",
  "",
  "use super::Icon;",
  "",
];
const idents = [];
for (const file of files) {
  const name = file.slice(0, -".svg".length);
  const svg = (await readFile(join(dir, file), "utf8")).replace(/<!--[\s\S]*?-->/g, "");
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
  if (!isPlainShapes(body) || body.includes('"#')) {
    throw new Error(`icon outside the allowlist: ${name}: ${body}`);
  }
  let ident = name.toUpperCase().replace(/[^A-Z0-9]+/g, "_");
  if (/^[0-9]/.test(ident)) ident = `N${ident}`;
  if (!/^[A-Z][A-Z0-9_]*$/.test(ident)) throw new Error(`bad identifier for ${name}`);
  idents.push(ident);
  lines.push(`/// Lucide \`${name}\`.`);
  lines.push(`pub const ${ident}: Icon = Icon::custom("${name}", r#"${body}"#);`);
}
lines.push("", "/// Every icon in the set, sorted by name.", "pub const ALL: &[Icon] = &[");
for (const ident of idents) lines.push(`    ${ident},`);
lines.push("];", "");

const out = join(here, "..", "crates", "stucco-ui", "src", "icon", "lucide.rs");
await writeFile(out, lines.join("\n"));
console.log(`wrote ${idents.length} icons (lucide-static ${version}) to ${out}`);
